// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vylmjmczfohdnklocwjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5bG1qbWN6Zm9oZG5rbG9jd2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzU2NDYsImV4cCI6MjA2MzYxMTY0Nn0.Hyia2WfQzpYZDTuzjjVKi6fovh84GueUG6Im2rKVlMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);